name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  NOMIC_CLEANUP_LEGACY_BUILD: 1

jobs:
  test-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-05-08
          override: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/src/**/librocksdb-sys-*
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cache-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --no-default-features --features=full,feat-ibc,testnet

  test-all-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-05-08
          override: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/src/**/librocksdb-sys-*
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cache-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features

  test-bitcoin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-05-08
          override: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/src/**/librocksdb-sys-*
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cache-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Test
        env:
          RUST_LOG: info
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all-features bitcoin -- --ignored

  check-rest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-05-08
          override: true
      - name: Check Rest
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path rest/Cargo.toml --verbose

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-05-08
          override: true
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build Wasm
        working-directory: ./wasm
        run: wasm-pack -v build --target web

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-05-08
          components: rustfmt
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-05-08
          components: clippy
          override: true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/src/**/librocksdb-sys-*
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cache-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features=full,feat-ibc,testnet -- -D warnings --no-deps
